# -*- coding: utf-8 -*-
"""DDP5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nUFn8cD8aYlejQVnrM1IamnlBxPVmTt5
"""

#Soal no 1
kendaraan = ["motor", "matic", 125, "hitam", 2]
print(kendaraan)
kendaraan.append(20000000)
kendaraan.append("Mio m3")
kendaraan.insert(3,"Yamaha")
print(kendaraan)

#soal no 2
Pilihan = int(input("masukan pilihan"))
persegi = "Luas Persegi: "
lingkaran= "Luas Lingkaran: "
segitiga= "Luas Segitiga"

match Pilihan:
 case 1 :
  print(persegi, int(input("Sisi: ")) **2)
 case 2 :
    print(lingkaran, 3.14 * int(input ("jari-jari")) **2)
 case 3 :
      print(segitiga, 1/2 * int(input("alas")) * int(input("tinggi")) )